services:
  - type: web
    name: resso-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && curl -fsSL https://deno.land/install.sh | sh
    startCommand: python bot.py
    healthCheckPath: /health
